<?xml version="1.0"?>
<!DOCTYPE rules [
	<!ELEMENT cars (car+)>
	<!ELEMENT car (name, model, prod_country, price, serial_number, prod_year, image, parameter_list?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT model (#PCDATA)>
	<!ELEMENT prod_country (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT serial_number (#PCDATA)>
	<!ELEMENT prod_year (#PCDATA)>
	<!ELEMENT image (#PCDATA)>
    <!ELEMENT parameter_list (parameter+)>
    <!ELEMENT parameter (parameter_name, parameter_value)>
    <!ELEMENT parameter_name (#PCDATA)>
    <!ELEMENT parameter_value (#PCDATA)>
    <!ATTLIST car
        price CDATA #REQUIRED
        id ID #REQUIRED
    >
]>
<cars>
	<car price="55 000" id="1">
		<name><![CDATA[Tesla]]></name>
		<model><![CDATA[Model 3]]></model>
		<prod_country><![CDATA[USA]]></prod_country>
		<serial_number><![CDATA[AE0929106]]></serial_number>
		<prod_year>2017</prod_year>
		<image><![CDATA[https://cdn.images.express.co.uk/img/dynamic/24/590x/Tesla-Model-3-1028468.jpg?r=1539006725919]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Battery]]></parameter_name>
                <parameter_value><![CDATA[62 kWh]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Electric range]]></parameter_name>
                <parameter_value><![CDATA[264 mi (420 km)]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="40 000" id="2">
		<name><![CDATA[Volkswagen]]></name>
		<model><![CDATA[Passat GT]]></model>
		<prod_country><![CDATA[Germany]]></prod_country>
		<serial_number><![CDATA[BE0129816]]></serial_number>
		<prod_year>2018</prod_year>
		<image><![CDATA[https://cnet4.cbsistatic.com/img/eNO-w--o-PVL0oz9zl4SDOAAvs0=/936x527/2018/03/26/350b9a38-581d-48ff-a2d3-9a2b23885471/2018-volkswagen-passat-gt-1.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Wheels]]></parameter_name>
                <parameter_value><![CDATA[Alloy wheels, 18" Oxford Anthracite]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Air conditioning]]></parameter_name>
                <parameter_value><![CDATA[3-zone automatic climate control with an improved anti-allergen filter]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Display]]></parameter_name>
                <parameter_value><![CDATA[12 inch high resolution TFT dash display screen with customisable menus and information.]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="51 400" id="3">
		<name><![CDATA[Volvo]]></name>
		<model><![CDATA[XC 90]]></model>
		<prod_country><![CDATA[Sweden]]></prod_country>
		<serial_number><![CDATA[EO8630784]]></serial_number>
		<prod_year><![CDATA[2016]]></prod_year>
		<image><![CDATA[https://st.motortrend.com/uploads/sites/10/2015/09/2016-Volvo-XC90-R-Design-front-side-view.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Short description]]></parameter_name>
                <parameter_value><![CDATA[Mid-size luxury crossover SUV manufactured and marketed by Volvo Cars since 2002 and now in its second generation]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="30 000" id="4">
		<name><![CDATA[Audi]]></name>
		<model><![CDATA[A4]]></model>
		<prod_country><![CDATA[Germany]]></prod_country>
		<serial_number><![CDATA[KE953859]]></serial_number>
		<prod_year>2010</prod_year>
		<image><![CDATA[https://assets.gocar.be/picserver1/userdata/1/25733/VmlTxhgqF/kfz43643555_bild1.jpg]]></image>
	</car>
	<car price="40 000" id="5">
		<name><![CDATA[BMW]]></name>
		<model><![CDATA[i3]]></model>
		<prod_country><![CDATA[Germany]]></prod_country>
		<serial_number><![CDATA[LK9683656]]></serial_number>
		<prod_year>2014</prod_year>
		<image><![CDATA[https://car-images.bauersecure.com/upload/31494/images/1040x585/0000c092f777-515e-4e71-a.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Class]]></parameter_name>
                <parameter_value><![CDATA[Subcompact (B) luxory vehicle]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Designer]]></parameter_name>
                <parameter_value><![CDATA[Richard Kim]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Engine]]></parameter_name>
                <parameter_value><![CDATA[W20K06U0 25 kW 647 cc, two-cylinder generator with a fuel tank capacity of 9 L]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="20 000" id="6">
		<name><![CDATA[Mercedes-Benz]]></name>
		<model><![CDATA[ML 350]]></model>
		<prod_country><![CDATA[Germany]]></prod_country>
		<serial_number><![CDATA[NB980698]]></serial_number>
		<prod_year>2008</prod_year>
		<image><![CDATA[https://www.conceptcarz.com/images/Mercedes-Benz/2010-Mercedes-Benz-M-Class-Image-02-800.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Seating]]></parameter_name>
                <parameter_value><![CDATA[5]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Horsepower]]></parameter_name>
                <parameter_value><![CDATA[380]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="15 500" id="7">
		<name><![CDATA[Honda]]></name>
		<model><![CDATA[Acord]]></model>
		<prod_country><![CDATA[Japan]]></prod_country>
		<serial_number><![CDATA[QK9986837]]></serial_number>
		<prod_year>2013</prod_year>
		<image><![CDATA[https://st.motortrend.com/uploads/sites/10/2015/11/2013-honda-accord-ex-l-v6-at-sedan-angular-front.png]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Engine]]></parameter_name>
                <parameter_value><![CDATA[2.4L I4 DOHC 16-valve]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Body]]></parameter_name>
                <parameter_value><![CDATA[Sedan]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Transmission]]></parameter_name>
                <parameter_value><![CDATA[6-speed manual transmission]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="20 000" id="8">
		<name><![CDATA[Chevrolet]]></name>
		<model><![CDATA[Equinox]]></model>
		<prod_country><![CDATA[USA]]></prod_country>
		<serial_number><![CDATA[OD8868403]]></serial_number>
		<prod_year>2014</prod_year>
		<image><![CDATA[https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/788x525/quality/85/https://s.aolcdn.com/commerce/autodata/images/USC30CHS152A021001.jpg]]></image>
	</car>
	<car price="15 000" id="9">
		<name><![CDATA[Dodge]]></name>
		<model><![CDATA[Grand Caravane]]></model>
		<prod_country><![CDATA[USA]]></prod_country>
		<serial_number><![CDATA[KG7595839]]></serial_number>
		<prod_year>2011</prod_year>
		<image><![CDATA[https://www.dickscott.com/assets/stock/colormatched_01/white/640/cc_2011dod003b_01_640/cc_2011dod003b_01_640_pw1.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Type]]></parameter_name>
                <parameter_value><![CDATA[Passenger van]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Pros]]></parameter_name>
                <parameter_value><![CDATA[Interior quality, one-touch Stow 'n Go second-row seats]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Cons]]></parameter_name>
                <parameter_value><![CDATA[Limited rearward travel for front seats, cheap airplane-style map lights]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
	<car price="22 000" id="10">
		<name><![CDATA[Mazda]]></name>
		<model><![CDATA[Mazda3]]></model>
		<prod_country><![CDATA[Japan]]></prod_country>
		<serial_number><![CDATA[XJ9583028]]></serial_number>
		<prod_year>2016</prod_year>
		<image><![CDATA[https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/788x525/quality/85/https://s.aolcdn.com/commerce/autodata/images/USC60MAC171D121001.jpg]]></image>
        <parameter_list>
            <parameter>
                <parameter_name><![CDATA[Color]]></parameter_name>
                <parameter_value><![CDATA[Gray]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Power]]></parameter_name>
                <parameter_value><![CDATA[155 hp @ 6000 rpm]]></parameter_value>
            </parameter>
            <parameter>
                <parameter_name><![CDATA[Power Steering]]></parameter_name>
                <parameter_value><![CDATA[Rack and pinion with engine-speed-sensing variable assist]]></parameter_value>
            </parameter>
        </parameter_list>
	</car>
</cars>
